name: Build and upload image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/llama_fact_checker:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Convert repository owner name to lowercase
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker tag ghcr.io/${{ github.repository_owner }}/llama_fact_checker:latest ghcr.io/${REPO_OWNER}/llama_fact_checker:latest

      - name: Push the Docker image to GHCR
        run: docker push ghcr.io/${REPO_OWNER}/llama_fact_checker:latest
